# Generated by Django 2.2.16 on 2021-03-22 17:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_name', models.CharField(max_length=100, unique=True)),
                ('service', models.CharField(max_length=100)),
                ('version', models.CharField(default='0.1', max_length=100)),
                ('title', models.CharField(default='New application', max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('categories', models.CharField(max_length=500)),
                ('website', models.CharField(max_length=500)),
                ('port', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(default='1', max_length=1)),
                ('installed', models.DateTimeField(default=django.utils.timezone.now)),
                ('enabled', models.BooleanField(default=1)),
                ('raw_options', models.CharField(default='', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('date', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='RemoteServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('url', models.TextField(max_length=250)),
                ('enabled', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('value', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('job_id', models.CharField(max_length=100)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('command', models.TextField(default='')),
                ('function', models.TextField(default='')),
                ('params', models.TextField(default='')),
                ('depend', models.TextField(default='')),
                ('incompatible', models.TextField(default='')),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=20)),
                ('last_login', models.CharField(default='', max_length=20)),
                ('session_id', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
