# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='incompatible',
            field=models.TextField(default=b''),
        ),
    ]
