# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_task_incompatible'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='raw_options',
            field=models.CharField(default=b'', max_length=2000),
        ),
    ]
