# Generated by Django 2.2.16 on 2020-12-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_user_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='raw_options',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='application',
            name='title',
            field=models.CharField(default='New application', max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='type',
            field=models.CharField(default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='application',
            name='version',
            field=models.CharField(default='0.1', max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='command',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='task',
            name='depend',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='task',
            name='function',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='task',
            name='incompatible',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='task',
            name='params',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='session_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
